### ISSUE TITLE
Should return a <table> component inside Table class

### ISSUE THREAD

**Issue by camunity** [xujuanchen2020/favLinks_20#1]
Hey sister your Table component should render a full `<table>` Currently you're returning a `<div>` Can you make this edit and resubmit?

**Comment by xujuanchen2020** [comment]
Hi Cam, I've fixed the codes, thank you so much!

**Comment by xujuanchen2020** [comment]
Hi Cam, I've fixed the codes, thank you so much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by camunity** [comment]
Great job @xujuanchen2020 !
